[project]
name = "logo-gmrt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.9.0",
    "matplotlib>=3.10.7",
]
