openapi: 3.1.0
info:
  title: pygmrt tile download
  version: 0.1.0
paths:
  /download:
    post:
      summary: Download a GMRT GeoTIFF tile for a bounding box
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                bbox:
                  $ref: "#/components/schemas/BoundingBox"
                resolution:
                  type: string
                  enum: [low, medium, high]
                  default: medium
                save_directory:
                  type: string
                overwrite:
                  type: boolean
                  default: false
              required: [bbox, save_directory]
      responses:
        "200":
          description: Download manifest
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DownloadResult"
        "400":
          description: Invalid input
components:
  schemas:
    BoundingBox:
      type: object
      properties:
        west: { type: number }
        south: { type: number }
        east: { type: number }
        north: { type: number }
      required: [west, south, east, north]
    ManifestEntry:
      type: object
      properties:
        path: { type: string }
        coverage:
          $ref: "#/components/schemas/BoundingBox"
        size_bytes: { type: integer }
        status: { type: string, enum: [created, reused] }
      required: [path, coverage, size_bytes, status]
    DownloadResult:
      type: object
      properties:
        entries:
          type: array
          items:
            $ref: "#/components/schemas/ManifestEntry"
        count_created: { type: integer }
        count_reused: { type: integer }
        errors:
          type: array
          items: { type: string }
      required: [entries, count_created, count_reused]
